// Constants
const DEPOSIT_METHOD = 'deposit'
const START_BYTE_SIZE = 12
const TYPE_BYTE_SIZE = 4
const TOKEN_ID_BYTE_SIZE = START_BYTE_SIZE + TYPE_BYTE_SIZE
const BLOCKNUMBER_BYTE_SIZE = 12

module.exports = {
  DEPOSIT_METHOD,
  START_BYTE_SIZE,
  TYPE_BYTE_SIZE,
  TOKEN_ID_BYTE_SIZE,
  BLOCKNUMBER_BYTE_SIZE
}
